### PR TITLE
Android Support for tio2

### PR DESCRIPTION
**Pull request by ashcoding**
Using the command: tio2 -p android -t device ./example -l debug

### CODE REVIEW

**Comment by ashcoding** [comment]
If you have a real device attached to your computer, in tio2 folder run:
```tio2 -p android -s 3.5.0.GA ../tests -l debug -t device```

If you have Genymotion running, in tio2 folder run:
```tio2 -p android -s 3.5.0.GA ../tests -l debug```

The `-l debug` tag is optional.

**Comment by ashcoding** [comment]
This PR depends on https://github.com/appcelerator/androidlib/pull/4. 
This PR would need to use the new androidlib for Android to work correctly. 
**Do not merge this yet.**

**Comment by ingo** [comment]
@ashcoding would you mind updating this PR? I published androidlib.

**Comment by ashcoding** [comment]
Ok! Will do.

**Comment by ashcoding** [comment]
Do not merge yet. Testing these new changes.

**Comment by ashcoding** [comment]
This can now be reviewed for testing.
Testing instructions:-
//Clone tio2 and checkout PR18
git clone https://github.com/appcelerator/tio2.git
cd tio2
git fetch origin pull/18/head:PR18
git checkout PR18
npm install
cd ..

//Clone the modified tests and checkout the branch
git clone https://github.com/ashcoding/titanium_mobile_tests.git
cd titanium_mobile_tests
git checkout Android_Support
cd ..

//At this point, please turn on your emulator for testing or connect your device for testing
cd tio2
cd bin
//This is for testing with emulator. A target tag '-t device' is needed for physical device.
./tio2 -p android -s 3.5.1.GA -l debug ../../titanium_mobile_tests

Note:- For physical device Android OS 5.0+, I seem to be getting some weird logcat bug.

**Comment by ashcoding** [comment]
Will try to figure out and work on getting it to automatically turn on an emulator so it can run on travis as well.

**Comment by ingo** [comment]
I can't seem to get the tests to run...I tried this both on titanium_mobile_tests and the included example. It seems to hang after launching the app:

```
2015-03-09T19:40:07.039Z - tio2-trace:  [DEBUG] Sending event: /Users/ingo/.titanium/events/2015-03-09T19-40-06.829Z_4003.json
2015-03-09T19:40:07.039Z - tio2-trace:  {
	"uri": "https://api.appcelerator.com/p/v1/app-track",
	"method": "POST",
	"headers": {
		"Cookie": "PHPSESSID=sgoetp6uh95m7ua1kt68jn62o4;uid=29abcd4cdf8a4d260909234877b16e6f"
	},
	"rejectUnauthorized": true,
	"body": "event=android.emulator.run&type=app.feature&sid=efe15cde-ada1-43fc-a81f-92cadcbcb585&guid=cf5c67ed-1c3b-494b-afe0-01b958ef0f40&mid=e6bb2c4e6843383d8cda2183f6c19c5a&mac_addr=&ip=&creator_user_id=1704957&app_name=Titanium%20Command-Line%20Interface&app_version=3.4.2&version=3.4.2&tz=420&ver=2&un=travisci%40appcelerator.com&data=%7B%22dir%22%3A%22%2Fvar%2Ffolders%2Fjf%2Fk0njrhzd5nb9q91mdm4ymr380000gp%2FT%2Ftio2_11529-35619-yj6cbk%22%2C%22name%22%3A%22test%22%2C%22publisher%22%3A%22not%20specified%22%2C%22url%22%3A%22%22%2C%22image%22%3A%22appicon.png%22%2C%22appid%22%3A%22com.appcelerator.test.tio%22%2C%22description%22%3A%22%22%2C%22type%22%3A%22app%22%2C%22guid%22%3A%22f6bb2c71-32b7-415a-8e2f-b423ee9bef2d%22%2C%22version%22%3A%221.0%22%2C%22copyright%22%3A%22not%20specified%22%2C%22date%22%3A%22Mon%20Mar%2009%202015%22%7D&id=38690c0a-29e5-415b-ab49-ee4de8b3c3a2&os=Mac%20OS%20X&platform=osx&osver=10.10.1&ostype=64bit&oscpu=8&memory=17179869184&node=0.12.0&npm=2.5.1"
}
2015-03-09T19:40:07.604Z - tio2-trace:  [DEBUG] Event sent successfully
2015-03-09T19:40:07.604Z - tio2-trace:  [DEBUG] Removing event: /Users/ingo/.titanium/events/2015-03-09T19-40-06.829Z_4003.json
[DEBUG] Deleting pid file: /Users/ingo/.titanium/analytics.pid
2015-03-09T19:40:07.604Z - tio2-trace:  [DEBUG] All events processed

[DEBUG] Press ENTER to redraw prompt
2015-03-09T19:40:07.612Z - tio2:        Running app
2015-03-09T19:40:07.612Z - tio2-debug:  Build directory: /var/folders/jf/k0njrhzd5nb9q91mdm4ymr380000gp/T/tio2_11529-35619-yj6cbk/build/android/bin/test.apk
2015-03-09T19:40:07.613Z - tio2:        Launching Android app on emulator
```

Thoughts?

**Comment by ashcoding** [comment]
If it reaches:-
```
2015-03-09T19:40:07.613Z - tio2:        Launching Android app on emulator
````
Tio2 is working alright up to that point. What's not happening is the logs being passed to the emulator in the correct way.

For titanium_mobile_tests, I had done some modifications so that the logs can be passed correctly without any error. Thus, I had a branch that you had to use as mentioned earlier in the testing methods. I'll try to check out what's happening.

I'll recheck this and the example.

One question, which version of Android are you using for this?

**Comment by ashcoding** [comment]
I just did some checks and realize the examples weren't updated for this. Will do that now.

**Comment by ashcoding** [comment]
```
./tio2 -p android -s 3.5.1.GA -l debug ../example
```
Should now work, assuming current path is in the bin directory. 

I also fixed the https://github.com/ashcoding/titanium_mobile_tests/tree/Android_Support branch. There was a slight problem in the logs being detected. Solved it now.

**Comment by feons** [comment]
@ingo, it's working for me with the exception of **filesystem** test suite not being able to install, also emulator has be launched prior to running the test suites.

**Comment by ingo** [comment]
Merging based on @feons feedback

**Pull request merged**
